"""init

Revision ID: 149c6810ac16
Revises: 
Create Date: 2026-05-19 16:32:17.283023

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '149c6810ac16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('requiredOrElectiveCourse', sa.String(length=64), nullable=False),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.Column('teacher', sa.String(length=64), nullable=False),
    sa.Column('core', sa.Boolean(), nullable=False),
    sa.Column('academicYearSemester', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_academicYearSemester'), 'classes', ['academicYearSemester'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_index(op.f('ix_classes_requiredOrElectiveCourse'), 'classes', ['requiredOrElectiveCourse'], unique=False)
    op.create_index(op.f('ix_classes_teacher'), 'classes', ['teacher'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('humanities', sa.Integer(), nullable=False),
    sa.Column('social_min', sa.Integer(), nullable=False),
    sa.Column('social_max', sa.Integer(), nullable=False),
    sa.Column('sciences_min', sa.Integer(), nullable=False),
    sa.Column('sciences_max', sa.Integer(), nullable=False),
    sa.Column('computer_min', sa.Integer(), nullable=False),
    sa.Column('computer_max', sa.Integer(), nullable=False),
    sa.Column('residential_min', sa.Integer(), nullable=False),
    sa.Column('residential_max', sa.Integer(), nullable=False),
    sa.Column('chinese_min', sa.Integer(), nullable=False),
    sa.Column('chinese_max', sa.Integer(), nullable=False),
    sa.Column('pe', sa.Integer(), nullable=False),
    sa.Column('foreign', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('eng_passed', sa.Boolean(), nullable=True),
    sa.Column('main_department_id', sa.Integer(), nullable=False),
    sa.Column('sec_main_department_id', sa.Integer(), nullable=True),
    sa.Column('sub_main1_department_id', sa.Integer(), nullable=True),
    sa.Column('sub_main2_department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['sec_main_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['sub_main1_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['sub_main2_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_main_department_id'), 'students', ['main_department_id'], unique=False)
    op.create_index(op.f('ix_students_sec_main_department_id'), 'students', ['sec_main_department_id'], unique=False)
    op.create_index(op.f('ix_students_sub_main1_department_id'), 'students', ['sub_main1_department_id'], unique=False)
    op.create_index(op.f('ix_students_sub_main2_department_id'), 'students', ['sub_main2_department_id'], unique=False)
    op.create_table('selected_classes',
    sa.Column('classid', sa.Integer(), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('ispassed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['classid'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['studentid'], ['students.id'], ),
    sa.PrimaryKeyConstraint('classid', 'studentid')
    )
    op.create_index(op.f('ix_selected_classes_classid'), 'selected_classes', ['classid'], unique=False)
    op.create_index(op.f('ix_selected_classes_studentid'), 'selected_classes', ['studentid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selected_classes_studentid'), table_name='selected_classes')
    op.drop_index(op.f('ix_selected_classes_classid'), table_name='selected_classes')
    op.drop_table('selected_classes')
    op.drop_index(op.f('ix_students_sub_main2_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_sub_main1_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_sec_main_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_main_department_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_classes_teacher'), table_name='classes')
    op.drop_index(op.f('ix_classes_requiredOrElectiveCourse'), table_name='classes')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_academicYearSemester'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
