"""add_chosen_category_to_selected_classes

Revision ID: a2ff83189978
Revises: 8d5a8c5b9f72
Create Date: 2026-06-10 14:17:24.403218

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2ff83189978'
down_revision = '8d5a8c5b9f72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selected_classes', sa.Column('chosen_category', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selected_classes', 'chosen_category')
    # ### end Alembic commands ###
